### ISSUE TITLE
[FEATURE] Add buttons for cache clearing

### ISSUE THREAD

**Issue by ste101** [a-r-m-i-n/fluid_page_cache#3]
There is a button for refreshing. A button for clearing and refreshing would be nice.

Also a cache clearing button for each record would be nice

**Comment by a-r-m-i-n** [comment]
Why not use those?
![image](https://github.com/a-r-m-i-n/fluid_page_cache/assets/1275298/7643cb27-8cdf-4215-b4ce-ca668ca19462)
